version: '3.9'
services:
  backend:
    build: ./backend
    container_name: web_clipper_backend
    ports:
      - "8000:8000"
    environment:
      # Add any required ENV vars
      EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  
  frontend:
    build: ./frontend
    container_name: web_clipper_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
